### ISSUE TITLE
Error: Cannot read property 'flatMap' of undefined

### ISSUE THREAD

**Issue by kutyel** [sparksp/elm-review-action#26]
I just added this extension to our github CI actions and this is what happened:

![Screenshot 2021-03-22 at 11 13 26](https://user-images.githubusercontent.com/5127501/111974373-a2597f80-8aff-11eb-8e12-3f6c3ee89ae1.png)

**Comment by sparksp** [comment]
Oh dear - this would never happen if it were written in Elm! It looks like the structure of `errors` isn't as expected. Thanks for the bug report, I'll try to fix this later.

**Comment by kutyel** [comment]
Thank you, no problem! Yes, I also really miss Elm when I am coding in other environments 🤣

**Comment by sparksp** [comment]
I'm mostly there with a fix for this but have run out of time this evening to tidy it up for a release. It's working for me now over at https://github.com/sparksp/elm-review-action/pull/28 - you might be able to target the branch 'fix-26' if you wanted to give it a test.

**Comment by kutyel** [comment]
Still broken but now the error message is different 😅 

![Screenshot 2021-03-24 at 11 48 42](https://user-images.githubusercontent.com/5127501/112298066-e468f980-8c96-11eb-8ec5-cf128ee6a686.png)

**Comment by sparksp** [comment]
That's great news! That means my fix is working, what you've got there is an error straight from `elm-review`. What's the layout of your project? Is your `elm.json` in the root folder? Or is it nested somewhere deeper? Can you get a `- run: elm-review` step to work temporarily, instead of `- uses: sparksp/elm-review-action`? That should help you know what options you'll need to get the action to work (since the action just runs `elm-review` for you).

**Comment by kutyel** [comment]
Actually is kinda weird because what I had before was just `elm-review` and with the extension it does not work 😟 
```
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: dashboard
    steps:
```
Maybe it is ignoring the `working-directory` of GH Actions? 🤔

**Comment by sparksp** [comment]
It [looks like](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun) the `working-directory` in your defaults only applies to `run` steps, rather than `uses` steps. I use a `working-directory` in the action's test workflow which seems to work just fine: [.github/workflows/test.yml](https://github.com/sparksp/elm-review-action/blob/fix-26/.github/workflows/test.yml#L30)

```yaml
    - name: Run elm-review
      uses: ./ # this action
      with:
        elm_review: npx --no-install elm-review
        # elm_json: elm.json
        elm_files: src/Good.elm
        working-directory: ${{ github.workspace }}/__tests__/elm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
